# -*- coding: utf-8 -*-
"""Exoplant Habitability.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rIFh0te7xet5PBrj1dA0qiFipgIq7pjp

**MODULE 1: LOAD DATA**
"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
import os

df = pd.read_csv("/content/sample_data/all_exoplanets_2021.csv")
print("Columns in DataFrame:", df.columns.tolist())

cols = [
    "Planet Name",
    "Mass",
    "Orbital Period Days",
    "Equilibrium Temperature",
    "Spectral Type",
    "Stellar Effective Temperature",
    "Stellar Mass",
    "Stellar Metallicity"
]

df = df[cols]
print("Data shape:", df.shape)
df.head()

"""**CLEAN DATA**"""

df.fillna(df.median(numeric_only=True), inplace=True)
df["Spectral Type"].fillna("Unknown", inplace=True)

df = pd.get_dummies(df, columns=["Spectral Type"])

"""**FEATURE ENGINEERING**"""

df["habitability_index"] = (
    (df["Equilibrium Temperature"].between(200, 350)).astype(int) +
    (df["Mass"] <= 10).astype(int)
)

df["stellar_index"] = (
    (df["Stellar Effective Temperature"].between(3000, 6000)).astype(int) +
    (df["Stellar Metallicity"] >= -0.5).astype(int)
)

"""**NORMALIZATION**"""

scaler = MinMaxScaler()
num_cols = df.select_dtypes(include=np.number).columns
df[num_cols] = scaler.fit_transform(df[num_cols])

"""**SAVE CLEAN DATA**"""

os.makedirs("data", exist_ok=True)
df.to_csv("/content/exoplanets_cleaned.csv", index=False)
print("Clean dataset saved")